####ThymeLeaf配置
#spring:
#  thymeleaf:
#    #prefix：指定模板所在的目录
#    prefix: classpath:/templates/
#    #check-tempate-location: 检查模板路径是否存在
#    check-template-location: true
#    #cache: 是否缓存，开发模式下设置为false，避免改了模板还要重启服务器，线上设置为true，可以提高性能。
#    cache: true
#    suffix:  .html
#    encoding: UTF-8
#    mode: HTML5
#mayikt:
#  name: 蚂蚁课堂余胜军
#  age: 22
#mayikt:
#  addres: www.mayikt.com
#  age: ${random.int(10)}
#  name: mayikt
#  info: info
spring:
  profiles:
    active: prd
server:
  ###端口号
  port: 8080
  servlet:
    ##设置springboot项目访问路径
    context-path: /mayikt
#logging:
#  config: classpath:log4j.properties